//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Pricer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP_Pricer.DataRessources", typeof(DataRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date; ZC025YR; ZC050YR; ZC075YR; ZC100YR; ZC125YR; ZC150YR; ZC175YR; ZC200YR; ZC225YR; ZC250YR; ZC275YR; ZC300YR; ZC325YR; ZC350YR; ZC375YR; ZC400YR; ZC425YR; ZC450YR; ZC475YR; ZC500YR; ZC525YR; ZC550YR; ZC575YR; ZC600YR; ZC625YR; ZC650YR; ZC675YR; ZC700YR; ZC725YR; ZC750YR; ZC775YR; ZC800YR; ZC825YR; ZC850YR; ZC875YR; ZC900YR; ZC925YR; ZC950YR; ZC975YR; ZC1000YR; ZC1025YR; ZC1050YR; ZC1075YR; ZC1100YR; ZC1125YR; ZC1150YR; ZC1175YR; ZC1200YR; ZC1225YR; ZC1250YR; ZC1275YR; ZC1300YR; ZC1325YR; ZC1350YR; ZC137 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string taux2 {
            get {
                return ResourceManager.GetString("taux2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date; ZC025YR; ZC050YR
        ///01/01/1993;1,1;1,1
        ///.
        /// </summary>
        public static string tauxlineaire {
            get {
                return ResourceManager.GetString("tauxlineaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date; ZC025YR; ZC050YR; ZC075YR; ZC100YR; ZC125YR; ZC150YR; ZC175YR; ZC200YR
        ///01/01/1993;0,001894777;0,0030135;0,004450681;0,006076978;0,007796785;0,009540584;0,011259098;0,01291864
        ///.
        /// </summary>
        public static string tauxtest {
            get {
                return ResourceManager.GetString("tauxtest", resourceCulture);
            }
        }
    }
}
